#!/bin/sh
# get tivodecode, mplayer, libfaac, libx264

  mkdir binaries

  cd tivodecode-0.2pre4
  export CFLAGS="-arch i386 -arch ppc"
  export LDFLAGS="-arch i386 -arch ppc"
  ./configure --disable-dependency-tracking
  make
  cp tivodecode ../binaries/tivodecode

   export CFLAGS='-arch i386'
   export LDFLAGS='-arch i386'
  cd x264
  ./configure
  make

  cd ../faac
  ./configure --without-mp4v2
  make libfaac

  cd ../mplayer
  ./configure --disable-png --enable-x264 --disable-mplayer --enable-faac --enable-faad-internal --with-extraincdir=/Users/yoav/src/faac/include/:/Users/yoav/src/x264 --with-extralibdir=/Users/yoav/src/faac/libfaac/.libs/:/Users/yoav/src/x264 --extra-libs-mencoder='-lx264 /Users/yoav/src/faac/libfaac/.libs/libfaac.a'
  make
  cp ./mencoder ../binaries/mencoder-i386

   export CFLAGS='-arch ppc'
   export LDFLAGS='-arch ppc'

   cd ../x264
   make distclean
   ./configure --host=ppc-apple-darwin --disable-asm
   make

  cd ../faac
  make distclean
   ./configure --host=ppc-apple-darwin --without-mp4v2
  make

  export OPATH=$PATH
  export PATH=.:$PATH
  echo '#!/bin/sh
echo powerpc
' > uname
  chmod a+rx uname
  ./configure --enable-altivec --disable-png --enable-x264 --disable-mplayer --enable-faac --enable-faad-internal --with-extraincdir=/Users/yoav/src/faac/include/:/Users/yoav/src/x264 --with-extralibdir=/Users/yoav/src/faac/libfaac/.libs/:/Users/yoav/src/x264 --extra-libs-mencoder='-lx264 /Users/yoav/src/faac/libfaac/.libs/libfaac.a'
  export PATH=$OPATH
  rm uname
  make
  cp ./mencoder ../binaries/mencoder-ppc

  cd ../binaries
  lipo -create mencoder-i386 mencoder-ppc -output mencoder
